apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.25.1
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml", "--base-id", "1"]
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      - name: auth-helper
        image: marcosdy/envoy-jwt-auth-helper:1.0.0
        imagePullPolicy: IfNotPresent
        args:  ["-config", "/run/envoy-jwt-auth-helper/config/envoy-jwt-auth-helper.conf"]
        ports:
        - containerPort: 9011
        volumeMounts:
        - name: envoy-jwt-auth-helper-config
          mountPath: "/run/envoy-jwt-auth-helper/config"
          readOnly: true
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      - name: frontend
        imagePullPolicy: IfNotPresent
        image: us.gcr.io/scytale-registry/symbank-webapp@sha256:a1c9b1d14e14bd1a4e75698a4f153680d2a08e6f8d1f2d7110bff63d39228a75
        command: ["/opt/symbank-webapp/symbank-webapp", "-config", "/run/symbank-webapp/config/symbank-webapp.conf"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: symbank-webapp-config
          mountPath: /run/symbank-webapp/config
      volumes:
      - name: envoy-config
        configMap:
          name: frontend-envoy
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
      - name: envoy-jwt-auth-helper-config
        configMap:
            name: "fe-envoy-jwt-auth-helper-config"
      - name: symbank-webapp-config
        configMap:
          name: symbank-webapp-config
