sudo: required
dist: bionic

language: minimal

services:
  - docker

env:
  - CHANGE_MINIKUBE_NONE_USER=true

before_script:
  # Make root mounted as rshared to fix kube-dns issues.
  - sudo mount --make-rshared /
  # Install conntrack which is required for minikube since v1.18.0
  - sudo apt-get install -y conntrack
  # Download kubectl, which is a requirement for using minikube.
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  # Download minikube.
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - sudo minikube start --vm-driver=none --bootstrapper=kubeadm
  # Fix the kubectl context, as it's often stale.
  - sudo chown -R $USER.$USER ~/.kube
  - sudo chown -R $USER.$USER ~/.minikube
  - minikube update-context
  # Wait for Kubernetes to be up and ready.
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

script:
  - ./k8s/test-all.sh

notifications:
    slack:
      rooms:
        secure: Qi1PEb02HD0158WkiQ/m1xMkJNw1T46dwmAHWUpHTyNrDHLmx7UDKAIL319uUF9g8lixpLQ4AHzMpusn/VbZz1ccWLuqgkeY8gLywbAFPuhnUSWVub8NFg3Otd85YvHXzConPV72clQxe/gCRLbEIzEsjpwVnvHFt/85wDvfvfygOx478Rcnm75ENNAMb0WNuhnX2pdiwwbkF/j95WBJ+nZLaULyZRYAvTAE67sBvlQqorKQ9KlTV75raBbQ95MOq7jKOgp/UtKcLtz0nJc/GxqV81TnRnryGPCNm2XW0IYlaUgBQHw86zcQc0VVxbjbqzmcS+Wh6uZRIY6pNSDjEllYRp18pj+tpQA/tImd/YvvUS9PrKO8hOW+EmrEIsBjVRhT8ikVcRRPRrOOFKzrB0FAWBRyc42FuqiuS7W/WhUIAZPMcd9Rtj8/Wrd4gm3j1uRiDccu5D7xI1YXdI3fG6AxYbN+Ah8V7AnCXiWL5rw+XOIrgRLmF3I8n5zYCQ24yaHV060ReHyPccpdvCQgINqs6dQTIU0BnmiOsudQqvovne5pjnjYBeURViQ7KZEDctaFBsYEZUKRAIhOsUiYF6GgV2YPCkKO+cOWueRKPc0f4r4rth+kO/8kWDhrqCSNOUgv5T34/TsUeSY0vrByWc5j/AFjJRRctU7WdB0q5X8=
