version: '3'
services:

  spire-server-stock:
    build: ./docker/spire-server-stockmarket.org
    hostname: spire-server-stock
    tty: true
    privileged: true
    volumes: 
      - ./docker/spire-server-stockmarket.org/conf:/opt/spire/conf/server

  spire-server-broker:
    build: ./docker/spire-server-broker.org
    hostname: spire-server-broker
    tty: true
    privileged: true
    volumes: 
      - ./docker/spire-server-broker.org/conf:/opt/spire/conf/server

  stock-quotes-service:
    build: ./docker/stock-quotes-service
    hostname: stock-quotes-service
    tty: true
    privileged: true
    links:
      - spire-server-stock
      
  broker-webapp:
    build: ./docker/broker-webapp
    hostname: broker-webapp
    tty: true
    privileged: true
    links:
      - spire-server-broker
      - stock-quotes-service
    ports:
      - 8080:8080
